pragma solidity 0.8.5;

contract CoreErrors {
    string internal constant ERROR_CORE_NOT_POOL = "CORE:NOT_POOL";
    string internal constant ERROR_CORE_CANT_BE_POOL = "CORE:CANT_BE_POOL";

    string internal constant ERROR_CORE_TICKER_WAS_CANCELLED = "CORE:TICKER_WAS_CANCELLED";
    string internal constant ERROR_CORE_SYNTHETIC_VALIDATION_ERROR = "CORE:SYNTHETIC_VALIDATION_ERROR";
    string internal constant ERROR_CORE_NOT_ENOUGH_TOKEN_ALLOWANCE = "CORE:NOT_ENOUGH_TOKEN_ALLOWANCE";

    string internal constant ERROR_CORE_ADDRESSES_AND_AMOUNTS_LENGTH_DO_NOT_MATCH =
        "CORE:ADDRESSES_AND_AMOUNTS_DO_NOT_MATCH";
    string internal constant ERROR_CORE_ADDRESSES_AND_DERIVATIVES_LENGTH_DOES_NOT_MATCH =
        "CORE:ADDRESSES_AND_DERIVATIVES_LENGTH_DOES_NOT_MATCH";

    string internal constant ERROR_CORE_EXECUTION_BEFORE_MATURITY_NOT_ALLOWED =
        "CORE:EXECUTION_BEFORE_MATURITY_NOT_ALLOWED";
    string internal constant ERROR_CORE_SYNTHETIC_EXECUTION_WAS_NOT_ALLOWED =
        "CORE:SYNTHETIC_EXECUTION_WAS_NOT_ALLOWED";
    string internal constant ERROR_CORE_INSUFFICIENT_POOL_BALANCE = "CORE:INSUFFICIENT_POOL_BALANCE";

    string internal constant ERROR_CORE_CANT_CANCEL_DUMMY_ORACLE_ID = "CORE:CANT_CANCEL_DUMMY_ORACLE_ID";
    string internal constant ERROR_CORE_CANCELLATION_IS_NOT_ALLOWED = "CORE:CANCELLATION_IS_NOT_ALLOWED";

    string internal constant ERROR_CORE_UNKNOWN_POSITION_TYPE = "CORE:UNKNOWN_POSITION_TYPE";
}
