pragma solidity 0.8.5;

contract SyntheticAggregatorErrors {
    string internal constant ERROR_SYNTHETIC_AGGREGATOR_DERIVATIVE_HASH_NOT_MATCH =
        "SYNTHETIC_AGGREGATOR:DERIVATIVE_HASH_NOT_MATCH";
    string internal constant ERROR_SYNTHETIC_AGGREGATOR_WRONG_MARGIN = "SYNTHETIC_AGGREGATOR:WRONG_MARGIN";
    string internal constant ERROR_SYNTHETIC_AGGREGATOR_COMMISSION_TOO_BIG = "SYNTHETIC_AGGREGATOR:COMMISSION_TOO_BIG";
}
