on: [push]

jobs:
  main_job:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.5]

    name: Solidity Security 
    steps:
    - uses: actions/checkout@v2
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DEBUG: false
        envkey_ETHERSCAN_KEY: 'abc'
        envkey_BSCSCAN_API_KEY: 'abc'
        envkey_BSC_MAINNET_ENDPOINT: 'abc'
        envkey_POLYGON_MAINNET_ENDPOINT: 'abc'
        envkey_MNEMONIC: 'test test test test test test test test test test test junk'
        envkey_INFURA_API_KEY: 'abc'
        directory: .
        file_name: .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run compile
    - name: Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v2
      with: 
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install slither
      run: |
        python -m pip install --upgrade pip
        pip3 install slither-analyzer
    - name: Run Slither
      run: |
        touch slither.txt
        slither --json . > slither.txt
      continue-on-error: true
    - name: Parse Slither result
      id: slither_result
      run: |
        high_detectors=$(cat slither.txt | grep -o '"impact": "High"' | wc -l)
        medium_detectors=$(cat slither.txt | grep -o '"impact": "Medium"' | wc -l)
    - name: Check medium warnings
      if: ${{steps.slither_result.outputs.medium_detectors > 15}}
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('More than 15 medium detectors')
    - name: Check high warnings
      if: ${{steps.slither_result.outputs.high_detectors > 5}}
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('More than 5 high detectors')

